version: '3'
services:
  project:
    build: ..
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app --reload
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ./:/root
