version: '3'
services:
  django:
    build: ./project
    command: sh -c "gunicorn --bind 0.0.0.0:8080 app.wsgi"
    volumes:
      - ./project:/project
      - static_data:/project/static
    expose:
      - 8080
    environment:
      - DEBUG=1